// Code generated by MockGen. DO NOT EDIT.
// Source: components/registry-facade/pkg/registry/layersource_ext_test.go

// Package mock_registry_test is a generated GoMock package.
package mock_registry_test
