// Code generated by MockGen. DO NOT EDIT.
// Source: components/public-api-server/pkg/billingservice/mock_billingservice/billingservice.go

// Package mock_mock_billingservice is a generated GoMock package.
package mock_mock_billingservice
