// Code generated by MockGen. DO NOT EDIT.
// Source: components/image-builder-mk3/pkg/resolve/resolve_mock_test.go

// Package mock_resolve_test is a generated GoMock package.
package mock_resolve_test
