// Code generated by MockGen. DO NOT EDIT.
// Source: components/image-builder-mk3/pkg/orchestrator/orchestrator_test.go

// Package mock_orchestrator is a generated GoMock package.
package mock_orchestrator
